### PR TITLE
Task-55247 : When downloading a file from the activity stream, the Exo app is closed automatically

### PR DESCRIPTION
**Pull request by wbenabdessalem**
Update on tssk related to onRequestPermissionsResult function to avoid crash

### CODE REVIEW

**Review by rdenarie — CHANGES_REQUESTED** [review]
Please add the related task in the PR title

**Comment by wbenabdessalem** [comment]
> Please add the related task in the PR title

Done

**Review by rdenarie — CHANGES_REQUESTED** [review]
The correct format is 
Task-XXXXX
Can you update please ?

**Comment by wbenabdessalem** [comment]
> The correct format is Task-XXXXX Can you update please ?

Done

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
